// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNVrf7G12qGbeTeZol_dHdoEH0xeK_h_o',
    appId: '1:919320523624:web:b8efc59abf642b7f2cdcdd',
    messagingSenderId: '919320523624',
    projectId: 'nutrigrow-4d9e6',
    authDomain: 'nutrigrow-4d9e6.firebaseapp.com',
    storageBucket: 'nutrigrow-4d9e6.firebasestorage.app',
    measurementId: 'G-R20FDPDE3D',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKYZiMyEQvMQiwNA69VIMLp2m9Ib4DiI4',
    appId: '1:919320523624:ios:703d88bfbccfaa3e2cdcdd',
    messagingSenderId: '919320523624',
    projectId: 'nutrigrow-4d9e6',
    storageBucket: 'nutrigrow-4d9e6.firebasestorage.app',
    iosBundleId: 'com.example.nutrigrow',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKYZiMyEQvMQiwNA69VIMLp2m9Ib4DiI4',
    appId: '1:919320523624:ios:703d88bfbccfaa3e2cdcdd',
    messagingSenderId: '919320523624',
    projectId: 'nutrigrow-4d9e6',
    storageBucket: 'nutrigrow-4d9e6.firebasestorage.app',
    iosBundleId: 'com.example.nutrigrow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNVrf7G12qGbeTeZol_dHdoEH0xeK_h_o',
    appId: '1:919320523624:web:fbf4607f253473272cdcdd',
    messagingSenderId: '919320523624',
    projectId: 'nutrigrow-4d9e6',
    authDomain: 'nutrigrow-4d9e6.firebaseapp.com',
    storageBucket: 'nutrigrow-4d9e6.firebasestorage.app',
    measurementId: 'G-YXHWD5NKE6',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8brSqnXvPtZmAACw7sKQR_rad6OxsCa8',
    appId: '1:919320523624:android:964745c460c30fed2cdcdd',
    messagingSenderId: '919320523624',
    projectId: 'nutrigrow-4d9e6',
    storageBucket: 'nutrigrow-4d9e6.firebasestorage.app',
  );
}
